import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PrintButton } from "@/components/print-button";
import { COMPANY_ADDRESS, COMPANY_NAME, COMPANY_PHONE, CONTACT_EMAIL } from "@/lib/contact";
import { prisma } from "@/lib/db";
import { formatMoney } from "@/lib/format";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Invoice" };

export default async function InvoicePage({ params }: { params: { id: string } }) {
  const order = await prisma.order.findUnique({ where: { id: params.id }, include: { items: true } });
  if (!order) notFound();
  const cur = order.currency;
  const isPaid = order.paymentStatus === "PAID";

  return (
    <main className="mx-auto max-w-3xl bg-white p-8 text-ink">
      <div className="mb-6 flex items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black">{isPaid ? "INVOICE 发票" : "PROFORMA INVOICE 形式发票"}</h1>
          <p className="mt-1 text-sm text-steel">No. {order.orderNumber} · {order.createdAt.toLocaleDateString("en-GB")}</p>
        </div>
        <PrintButton />
      </div>

      <div className="grid grid-cols-2 gap-6 border-y border-line py-4 text-sm">
        <div>
          <p className="font-black uppercase text-steel">From</p>
          <p className="mt-1 font-bold">{COMPANY_NAME}</p>
          {COMPANY_ADDRESS && <p className="text-steel">{COMPANY_ADDRESS}</p>}
          {COMPANY_PHONE && <p className="text-steel">{COMPANY_PHONE}</p>}
          <p className="text-steel">{CONTACT_EMAIL}</p>
        </div>
        <div>
          <p className="font-black uppercase text-steel">Bill to</p>
          <p className="mt-1 font-bold">{order.customerName}</p>
          <p className="text-steel">{order.customerEmail}</p>
          <p className="text-steel">{[order.shippingAddress, order.city, order.postalCode, order.country].filter(Boolean).join(", ")}</p>
          {order.customerPhone && <p className="text-steel">{order.customerPhone}</p>}
        </div>
      </div>

      <table className="mt-6 w-full text-left text-sm">
        <thead className="border-b border-ink">
          <tr>
            <th className="py-2">Item</th>
            <th className="py-2">SKU</th>
            <th className="py-2 text-right">Unit</th>
            <th className="py-2 text-right">Qty</th>
            <th className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((item) => (
            <tr key={item.id} className="border-b border-line">
              <td className="py-2">{item.productName}</td>
              <td className="py-2 text-steel">{item.sku}</td>
              <td className="py-2 text-right">{formatMoney(item.unitPriceCents, cur)}</td>
              <td className="py-2 text-right">{item.quantity}</td>
              <td className="py-2 text-right">{formatMoney(item.subtotalCents, cur)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-4 ml-auto grid max-w-xs gap-1 text-sm">
        <Row label="Subtotal" value={formatMoney(order.subtotalCents, cur)} />
        {order.discountCents > 0 && <Row label="Discount" value={`-${formatMoney(order.discountCents, cur)}`} />}
        <Row label="Shipping" value={formatMoney(order.shippingCents, cur)} />
        {order.taxCents > 0 && <Row label="incl. VAT/tax" value={formatMoney(order.taxCents, cur)} />}
        <div className="mt-1 flex justify-between border-t border-ink pt-2 text-base font-black">
          <span>Total</span>
          <span>{formatMoney(order.totalCents, cur)}</span>
        </div>
        {order.refundedCents > 0 && <Row label="Refunded" value={`-${formatMoney(order.refundedCents, cur)}`} />}
      </div>

      <p className="mt-8 text-xs text-steel">
        {isPaid ? `Paid via ${order.paymentMethod} on ${order.paidAt ? order.paidAt.toLocaleDateString("en-GB") : "-"}.` : "Payment pending."}
        {" "}This invoice was generated by {COMPANY_NAME}.
      </p>
    </main>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between text-steel">
      <span>{label}</span>
      <span className="font-bold text-ink">{value}</span>
    </div>
  );
}
